### ISSUE TITLE
Dice Roller Features

### ISSUE THREAD

**Issue by tawilkinson** [stevebot-project/steve#1]
**What would you like Steve to do?**

Mostly for Modventure Zone purpose but the following options would be useful:

- `s;roll 1d8 + 4d6` **Reason:** Allows multiple dice to be combined for things like attack rolls and sneak attack. 
- `s;roll 2d20k1` **Reason:** Allows rolling multiple dice and keeping the highest x (Useful for Advantage in D&D)
- `s;roll 2d20kl1` **Reason:** Allows rolling multiple dice and keeping the lowest x (Useful for Disadvantage in D&D)
- `s;roll d20` **Reason:** Steve should be able to guess this is 1d20.

There are many more options (see: https://github.com/ArtemGr/Sidekick) but the above should be sufficient for now

**Comment by jwford** [comment]
I haven't forgotten the last time you suggested this, that's how exploding dice found their way into the latest verison 😛 Will work on these for the next release though!

**Comment by stephenwade** [comment]
The Sidekick bot that @tawilkinson linked to is MIT licensed. Could it just be pulled into this project and used for the `s;roll` command?

**Comment by jwford** [comment]
It is under MIT but I don't see any actual code in that repository to pull into this one.

**Comment by stephenwade** [comment]
Oh wow, I should've noticed that. Whoops.

Would you be open to PRs implementing some of this?

**Comment by jwford** [comment]
Sure! 😃

**Comment by jwford** [comment]
@tawilkinson when's the next modventure zone? monday again?
