### ISSUE TITLE
localization 

### ISSUE THREAD

**Issue by jwford** [stevebot-project/steve#22]
Use Klasa's Language features to localize the bot, in preparation for *maybe* supporting multiple languages

**Comment by colinkautz** [comment]
If you haven't already, I found some of the other language files that seem to have most of what is in the en-US file we use. https://github.com/KlasaCommunityPlugins/klasa-pieces-ts/tree/master/languages

**Comment by jwford** [comment]
Yeah klasa-pieces has a lot of language files for what comes with klasa, was mainly talking about everything that we made him say that doesn't come with klasa lol

**Comment by colinkautz** [comment]
that's fair. we could resource people from tua to make sure it's accurately translated

**Comment by jwford** [comment]
that's the plan if/when we get to that point
first there's a lot of refactoring to do to allow that lol

**Comment by jwford** [comment]
closed by 6065ceb
